//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2")]
    public partial class AccessDeniedException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2")]
    public partial class OperationFailedException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2")]
    public partial class InvalidParametersException
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2")]
    public partial class ConnectException
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", ConfigurationName="ServiceReference2.SecurityService")]
    public interface SecurityService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createRoleReturn")]
        System.Threading.Tasks.Task<bool> createRoleAsync(string roleName, string description, string adminUser, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createUserReturn")]
        System.Threading.Tasks.Task<bool> createUserAsync(string userName, string password, string adminUser, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="loginReturn")]
        System.Threading.Tasks.Task<string> loginAsync(string userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getSecurityModelReturn")]
        System.Threading.Tasks.Task<string> getSecurityModelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isReportDeveloperReturn")]
        System.Threading.Tasks.Task<bool> isReportDeveloperAsync(string userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isDataModelDeveloperReturn")]
        System.Threading.Tasks.Task<bool> isDataModelDeveloperAsync(string userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isAdminReturn")]
        System.Threading.Tasks.Task<bool> isAdminAsync(string userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="impersonateReturn")]
        System.Threading.Tasks.Task<string> impersonateAsync(string adminUsername, string adminPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateUserReturn")]
        System.Threading.Tasks.Task<bool> updateUserAsync(string currentUsername, string newPassword, string adminUser, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="updateRoleReturn")]
        System.Threading.Tasks.Task<bool> updateRoleAsync(string currentRoleName, string newDescription, string adminUser, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="deleteRoleReturn")]
        System.Threading.Tasks.Task<bool> deleteRoleAsync(string roleName, string adminUser, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="deleteUserReturn")]
        System.Threading.Tasks.Task<bool> deleteUserAsync(string userName, string adminUser, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isSchedulerReturn")]
        System.Threading.Tasks.Task<bool> isSchedulerAsync(string userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isOnlineAnalyzerReturn")]
        System.Threading.Tasks.Task<bool> isOnlineAnalyzerAsync(string userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isExcelAnalyzerReturn")]
        System.Threading.Tasks.Task<bool> isExcelAnalyzerAsync(string userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="logoutReturn")]
        System.Threading.Tasks.Task<bool> logoutAsync(string bipSessionToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="validateLoginReturn")]
        System.Threading.Tasks.Task<bool> validateLoginAsync(string userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="isUserExistsReturn")]
        System.Threading.Tasks.Task<bool> isUserExistsAsync(string userName, string adminUser, string adminPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.assignRolesToUserResponse> assignRolesToUserAsync(ServiceReference2.assignRolesToUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.removeRolesFromUserResponse> removeRolesFromUserAsync(ServiceReference2.removeRolesFromUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.ConnectException), Action="", Name="fault3")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="notifyBIEEPreferencesUpdatedWithStringReturn")]
        System.Threading.Tasks.Task<bool> notifyBIEEPreferencesUpdatedWithStringAsync(string bieeSessionID, string userPrefesXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="notifyBIEEPreferencesUpdatedReturn")]
        System.Threading.Tasks.Task<bool> notifyBIEEPreferencesUpdatedAsync(string bieeSessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getBIPHTTPSessionIntervalReturn")]
        System.Threading.Tasks.Task<int> getBIPHTTPSessionIntervalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.checkObjectPermissionsResponse> checkObjectPermissionsAsync(ServiceReference2.checkObjectPermissionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.InvalidParametersException), Action="", Name="fault2")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.checkObjectPermissionsInSessionResponse> checkObjectPermissionsInSessionAsync(ServiceReference2.checkObjectPermissionsInSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.AccessDeniedException), Action="", Name="fault1")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReference2.OperationFailedException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.getObjectSecurityXMLResponse> getObjectSecurityXMLAsync(ServiceReference2.getObjectSecurityXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="assignRolesToUser", WrapperNamespace="http://xmlns.oracle.com/oxp/service/v2", IsWrapped=true)]
    public partial class assignRolesToUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] roleNames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=2)]
        public string adminUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=3)]
        public string adminPassword;
        
        public assignRolesToUserRequest()
        {
        }
        
        public assignRolesToUserRequest(string userName, string[] roleNames, string adminUser, string adminPassword)
        {
            this.userName = userName;
            this.roleNames = roleNames;
            this.adminUser = adminUser;
            this.adminPassword = adminPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="assignRolesToUserResponse", WrapperNamespace="http://xmlns.oracle.com/oxp/service/v2", IsWrapped=true)]
    public partial class assignRolesToUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] assignRolesToUserReturn;
        
        public assignRolesToUserResponse()
        {
        }
        
        public assignRolesToUserResponse(string[] assignRolesToUserReturn)
        {
            this.assignRolesToUserReturn = assignRolesToUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeRolesFromUser", WrapperNamespace="http://xmlns.oracle.com/oxp/service/v2", IsWrapped=true)]
    public partial class removeRolesFromUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=0)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] roleNames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=2)]
        public string adminUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=3)]
        public string adminPassword;
        
        public removeRolesFromUserRequest()
        {
        }
        
        public removeRolesFromUserRequest(string userName, string[] roleNames, string adminUser, string adminPassword)
        {
            this.userName = userName;
            this.roleNames = roleNames;
            this.adminUser = adminUser;
            this.adminPassword = adminPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeRolesFromUserResponse", WrapperNamespace="http://xmlns.oracle.com/oxp/service/v2", IsWrapped=true)]
    public partial class removeRolesFromUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] removeRolesFromUserReturn;
        
        public removeRolesFromUserResponse()
        {
        }
        
        public removeRolesFromUserResponse(string[] removeRolesFromUserReturn)
        {
            this.removeRolesFromUserReturn = removeRolesFromUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkObjectPermissions", WrapperNamespace="http://xmlns.oracle.com/oxp/service/v2", IsWrapped=true)]
    public partial class checkObjectPermissionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=0)]
        public string objectAbsolutePath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] privileges;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=2)]
        public string userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=3)]
        public string password;
        
        public checkObjectPermissionsRequest()
        {
        }
        
        public checkObjectPermissionsRequest(string objectAbsolutePath, string[] privileges, string userID, string password)
        {
            this.objectAbsolutePath = objectAbsolutePath;
            this.privileges = privileges;
            this.userID = userID;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkObjectPermissionsResponse", WrapperNamespace="http://xmlns.oracle.com/oxp/service/v2", IsWrapped=true)]
    public partial class checkObjectPermissionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("checkObjectPermissionsReturn")]
        public bool[] checkObjectPermissionsReturn;
        
        public checkObjectPermissionsResponse()
        {
        }
        
        public checkObjectPermissionsResponse(bool[] checkObjectPermissionsReturn)
        {
            this.checkObjectPermissionsReturn = checkObjectPermissionsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkObjectPermissionsInSession", WrapperNamespace="http://xmlns.oracle.com/oxp/service/v2", IsWrapped=true)]
    public partial class checkObjectPermissionsInSessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=0)]
        public string objectAbsolutePath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] privileges;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=2)]
        public string bipSessionToken;
        
        public checkObjectPermissionsInSessionRequest()
        {
        }
        
        public checkObjectPermissionsInSessionRequest(string objectAbsolutePath, string[] privileges, string bipSessionToken)
        {
            this.objectAbsolutePath = objectAbsolutePath;
            this.privileges = privileges;
            this.bipSessionToken = bipSessionToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkObjectPermissionsInSessionResponse", WrapperNamespace="http://xmlns.oracle.com/oxp/service/v2", IsWrapped=true)]
    public partial class checkObjectPermissionsInSessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("checkObjectPermissionsInSessionReturn")]
        public bool[] checkObjectPermissionsInSessionReturn;
        
        public checkObjectPermissionsInSessionResponse()
        {
        }
        
        public checkObjectPermissionsInSessionResponse(bool[] checkObjectPermissionsInSessionReturn)
        {
            this.checkObjectPermissionsInSessionReturn = checkObjectPermissionsInSessionReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getObjectSecurityXML", WrapperNamespace="http://xmlns.oracle.com/oxp/service/v2", IsWrapped=true)]
    public partial class getObjectSecurityXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=0)]
        public string adminUsername;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=1)]
        public string adminPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=2)]
        public string objectAbsolutePath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=3)]
        public bool isRecursive;
        
        public getObjectSecurityXMLRequest()
        {
        }
        
        public getObjectSecurityXMLRequest(string adminUsername, string adminPassword, string objectAbsolutePath, bool isRecursive)
        {
            this.adminUsername = adminUsername;
            this.adminPassword = adminPassword;
            this.objectAbsolutePath = objectAbsolutePath;
            this.isRecursive = isRecursive;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getObjectSecurityXMLResponse", WrapperNamespace="http://xmlns.oracle.com/oxp/service/v2", IsWrapped=true)]
    public partial class getObjectSecurityXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/oxp/service/v2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getObjectSecurityXMLReturn;
        
        public getObjectSecurityXMLResponse()
        {
        }
        
        public getObjectSecurityXMLResponse(byte[] getObjectSecurityXMLReturn)
        {
            this.getObjectSecurityXMLReturn = getObjectSecurityXMLReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SecurityServiceChannel : ServiceReference2.SecurityService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<ServiceReference2.SecurityService>, ServiceReference2.SecurityService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SecurityServiceClient() : 
                base(SecurityServiceClient.GetDefaultBinding(), SecurityServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SecurityService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SecurityServiceClient.GetBindingForEndpoint(endpointConfiguration), SecurityServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SecurityServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SecurityServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> createRoleAsync(string roleName, string description, string adminUser, string adminPassword)
        {
            return base.Channel.createRoleAsync(roleName, description, adminUser, adminPassword);
        }
        
        public System.Threading.Tasks.Task<bool> createUserAsync(string userName, string password, string adminUser, string adminPassword)
        {
            return base.Channel.createUserAsync(userName, password, adminUser, adminPassword);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(string userID, string password)
        {
            return base.Channel.loginAsync(userID, password);
        }
        
        public System.Threading.Tasks.Task<string> getSecurityModelAsync()
        {
            return base.Channel.getSecurityModelAsync();
        }
        
        public System.Threading.Tasks.Task<bool> isReportDeveloperAsync(string userID, string password)
        {
            return base.Channel.isReportDeveloperAsync(userID, password);
        }
        
        public System.Threading.Tasks.Task<bool> isDataModelDeveloperAsync(string userID, string password)
        {
            return base.Channel.isDataModelDeveloperAsync(userID, password);
        }
        
        public System.Threading.Tasks.Task<bool> isAdminAsync(string userID, string password)
        {
            return base.Channel.isAdminAsync(userID, password);
        }
        
        public System.Threading.Tasks.Task<string> impersonateAsync(string adminUsername, string adminPassword, string username)
        {
            return base.Channel.impersonateAsync(adminUsername, adminPassword, username);
        }
        
        public System.Threading.Tasks.Task<bool> updateUserAsync(string currentUsername, string newPassword, string adminUser, string adminPassword)
        {
            return base.Channel.updateUserAsync(currentUsername, newPassword, adminUser, adminPassword);
        }
        
        public System.Threading.Tasks.Task<bool> updateRoleAsync(string currentRoleName, string newDescription, string adminUser, string adminPassword)
        {
            return base.Channel.updateRoleAsync(currentRoleName, newDescription, adminUser, adminPassword);
        }
        
        public System.Threading.Tasks.Task<bool> deleteRoleAsync(string roleName, string adminUser, string adminPassword)
        {
            return base.Channel.deleteRoleAsync(roleName, adminUser, adminPassword);
        }
        
        public System.Threading.Tasks.Task<bool> deleteUserAsync(string userName, string adminUser, string adminPassword)
        {
            return base.Channel.deleteUserAsync(userName, adminUser, adminPassword);
        }
        
        public System.Threading.Tasks.Task<bool> isSchedulerAsync(string userID, string password)
        {
            return base.Channel.isSchedulerAsync(userID, password);
        }
        
        public System.Threading.Tasks.Task<bool> isOnlineAnalyzerAsync(string userID, string password)
        {
            return base.Channel.isOnlineAnalyzerAsync(userID, password);
        }
        
        public System.Threading.Tasks.Task<bool> isExcelAnalyzerAsync(string userID, string password)
        {
            return base.Channel.isExcelAnalyzerAsync(userID, password);
        }
        
        public System.Threading.Tasks.Task<bool> logoutAsync(string bipSessionToken)
        {
            return base.Channel.logoutAsync(bipSessionToken);
        }
        
        public System.Threading.Tasks.Task<bool> validateLoginAsync(string userID, string password)
        {
            return base.Channel.validateLoginAsync(userID, password);
        }
        
        public System.Threading.Tasks.Task<bool> isUserExistsAsync(string userName, string adminUser, string adminPassword)
        {
            return base.Channel.isUserExistsAsync(userName, adminUser, adminPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.assignRolesToUserResponse> ServiceReference2.SecurityService.assignRolesToUserAsync(ServiceReference2.assignRolesToUserRequest request)
        {
            return base.Channel.assignRolesToUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.assignRolesToUserResponse> assignRolesToUserAsync(string userName, string[] roleNames, string adminUser, string adminPassword)
        {
            ServiceReference2.assignRolesToUserRequest inValue = new ServiceReference2.assignRolesToUserRequest();
            inValue.userName = userName;
            inValue.roleNames = roleNames;
            inValue.adminUser = adminUser;
            inValue.adminPassword = adminPassword;
            return ((ServiceReference2.SecurityService)(this)).assignRolesToUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.removeRolesFromUserResponse> ServiceReference2.SecurityService.removeRolesFromUserAsync(ServiceReference2.removeRolesFromUserRequest request)
        {
            return base.Channel.removeRolesFromUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.removeRolesFromUserResponse> removeRolesFromUserAsync(string userName, string[] roleNames, string adminUser, string adminPassword)
        {
            ServiceReference2.removeRolesFromUserRequest inValue = new ServiceReference2.removeRolesFromUserRequest();
            inValue.userName = userName;
            inValue.roleNames = roleNames;
            inValue.adminUser = adminUser;
            inValue.adminPassword = adminPassword;
            return ((ServiceReference2.SecurityService)(this)).removeRolesFromUserAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> notifyBIEEPreferencesUpdatedWithStringAsync(string bieeSessionID, string userPrefesXML)
        {
            return base.Channel.notifyBIEEPreferencesUpdatedWithStringAsync(bieeSessionID, userPrefesXML);
        }
        
        public System.Threading.Tasks.Task<bool> notifyBIEEPreferencesUpdatedAsync(string bieeSessionID)
        {
            return base.Channel.notifyBIEEPreferencesUpdatedAsync(bieeSessionID);
        }
        
        public System.Threading.Tasks.Task<int> getBIPHTTPSessionIntervalAsync()
        {
            return base.Channel.getBIPHTTPSessionIntervalAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.checkObjectPermissionsResponse> ServiceReference2.SecurityService.checkObjectPermissionsAsync(ServiceReference2.checkObjectPermissionsRequest request)
        {
            return base.Channel.checkObjectPermissionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.checkObjectPermissionsResponse> checkObjectPermissionsAsync(string objectAbsolutePath, string[] privileges, string userID, string password)
        {
            ServiceReference2.checkObjectPermissionsRequest inValue = new ServiceReference2.checkObjectPermissionsRequest();
            inValue.objectAbsolutePath = objectAbsolutePath;
            inValue.privileges = privileges;
            inValue.userID = userID;
            inValue.password = password;
            return ((ServiceReference2.SecurityService)(this)).checkObjectPermissionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.checkObjectPermissionsInSessionResponse> ServiceReference2.SecurityService.checkObjectPermissionsInSessionAsync(ServiceReference2.checkObjectPermissionsInSessionRequest request)
        {
            return base.Channel.checkObjectPermissionsInSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.checkObjectPermissionsInSessionResponse> checkObjectPermissionsInSessionAsync(string objectAbsolutePath, string[] privileges, string bipSessionToken)
        {
            ServiceReference2.checkObjectPermissionsInSessionRequest inValue = new ServiceReference2.checkObjectPermissionsInSessionRequest();
            inValue.objectAbsolutePath = objectAbsolutePath;
            inValue.privileges = privileges;
            inValue.bipSessionToken = bipSessionToken;
            return ((ServiceReference2.SecurityService)(this)).checkObjectPermissionsInSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.getObjectSecurityXMLResponse> ServiceReference2.SecurityService.getObjectSecurityXMLAsync(ServiceReference2.getObjectSecurityXMLRequest request)
        {
            return base.Channel.getObjectSecurityXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.getObjectSecurityXMLResponse> getObjectSecurityXMLAsync(string adminUsername, string adminPassword, string objectAbsolutePath, bool isRecursive)
        {
            ServiceReference2.getObjectSecurityXMLRequest inValue = new ServiceReference2.getObjectSecurityXMLRequest();
            inValue.adminUsername = adminUsername;
            inValue.adminPassword = adminPassword;
            inValue.objectAbsolutePath = objectAbsolutePath;
            inValue.isRecursive = isRecursive;
            return ((ServiceReference2.SecurityService)(this)).getObjectSecurityXMLAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecurityService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SecurityService))
            {
                return new System.ServiceModel.EndpointAddress("https://fa-ewnb-test-saasfaprod1.fa.ocs.oraclecloud.com/xmlpserver/services/v2/Se" +
                        "curityService");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SecurityServiceClient.GetBindingForEndpoint(EndpointConfiguration.SecurityService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SecurityServiceClient.GetEndpointAddress(EndpointConfiguration.SecurityService);
        }
        
        public enum EndpointConfiguration
        {
            
            SecurityService,
        }
    }
}
