<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="8.0.6" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Api\WebApi.Booking.Api\WebApi.Booking.Api.csproj" />
    <ProjectReference Include="..\..\Common\WebApi.Booking.Common\WebApi.Booking.Common.csproj" />
    <ProjectReference Include="..\..\Core\WebApi.Booking.Application\WebApi.Booking.Application.csproj" />
    <ProjectReference Include="..\..\Core\WebApi.Booking.Domain\WebApi.Booking.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\WebApi.Booking.External\WebApi.Booking.External.csproj" />
    <ProjectReference Include="..\..\Infrastructure\WebApi.Booking.Persistence\WebApi.Booking.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
